[reticulum]
  enable_transport = Yes
  share_instance = Yes
  instance_name = default

[logging]
  loglevel = 4

[interfaces]
  [[Default Interface]]
    type = AutoInterface
    enabled = Yes

  [[VPS TCP Server]]
    type = TCPServerInterface
    enabled = Yes
    listen_ip = 0.0.0.0
    listen_port = 49200

  [[MichMesh Testnet]]
    type = TCPClientInterface
    enabled = yes
    target_host = RNS.MichMesh.net
    target_port = 7822
    ifac_size = 6

  [[Minuteman RNS]]
    type = TCPClientInterface
    enabled = yes
    target_host = rns.karkom.net
    target_port = 4242
    ifac_size = 6

  [[UTN Oregon]]
    type = TCPClientInterface
    enabled = yes
    target_host = rns.utn.lol
    target_port = 4965
    ifac_size = 6

  [[ShadowLink]]
    type = TCPClientInterface
    enabled = yes
    target_host = shadownode.teske.live
    target_port = 4242
    ifac_size = 6
